/**
 * @file ucifi_lamp.h
 * @brief Resource IDs for uCIFI Outdoor Lamp Controller object (ID: 3416)
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __LWM2M_UCIFI_LAMP__
#define __LWM2M_UCIFI_LAMP__

#define UCIFI_OBJECT_LAMP_ID              3416

/* uCIFI Lamp resource IDs */
#define UCIFI_LAMP_COMMAND_RID            	       1
#define UCIFI_LAMP_COMMAND_IN_ACTION_RID           2
#define UCIFI_LAMP_DIMMING_LEVEL_RID      	       3
#define UCIFI_LAMP_DEFAULT_DIMMING_LEVEL_RID       4
#define UCIFI_LAMP_FAILURE_RID         		       5
#define UCIFI_LAMP_LAMP_FAILURE_REASON_RID         6
#define UCIFI_LAMP_CONTROL_GEAR_FAILURE_RID        7
#define UCIFI_LAMP_CONTROL_GEAR_FAILURE_REASON_RID 8
#define UCIFI_LAMP_RELAY_FAILURE_RID               9
#define UCIFI_LAMP_DAY_BURNER_RID                  10
#define UCIFI_LAMP_CYCLING_FAILURE_RID             11
#define UCIFI_LAMP_CONTROL_GEAR_COMM_FAILURE_RID   12
/* 13, 14 were present in older specs; removed in 3.0 */
#define UCIFI_LAMP_OPERATING_HOURS_RID  	       15
#define UCIFI_LAMP_RESET_HOURS_RID        	       16
#define UCIFI_LAMP_ON_TIMESTAMP_RID                17
#define UCIFI_LAMP_SWITCH_COUNTER_RID              18
#define UCIFI_LAMP_SWITCH_COUNTER_RESET_RID        19
#define UCIFI_LAMP_CG_START_COUNTER_RID            20
#define UCIFI_LAMP_CG_TEMPERATURE_RID              21
#define UCIFI_LAMP_CG_THERMAL_DERATING_RID         22
#define UCIFI_LAMP_CG_THERMAL_DERATING_COUNTER_RID 23
#define UCIFI_LAMP_CG_THERMAL_DERATING_RESET_RID   24
#define UCIFI_LAMP_CG_THERMAL_SHUTDOWN_RID         25
#define UCIFI_LAMP_CG_THERMAL_SHUTDOWN_COUNTER_RID 26
#define UCIFI_LAMP_CG_THERMAL_SHUTDOWN_RESET_RID   27
#define UCIFI_LAMP_OUTPUT_PORT_RID                 28
#define UCIFI_LAMP_STANDBY_MODE_RID                29
#define UCIFI_LAMP_CONSTANT_LIGHT_OUTPUT_RID       30
#define UCIFI_LAMP_CLEANING_FACTOR_ENABLED_RID     31
#define UCIFI_LAMP_CLEANING_PERIOD_RID             32
#define UCIFI_LAMP_INITIAL_CLEANING_FACTOR_RID     33
#define UCIFI_LAMP_CLEANING_DATE_RID               34
#define UCIFI_LAMP_CONTROL_TYPE_RID                35
#define UCIFI_LAMP_NOMINAL_WATTAGE_RID             36
#define UCIFI_LAMP_MIN_DIMMING_LEVEL_RID           37
#define UCIFI_LAMP_MIN_WATTAGE_RID                 38
#define UCIFI_LAMP_COLOR_TEMP_CMD_RID              39
#define UCIFI_LAMP_COLOR_TEMP_ACTUAL_RID           40
#define UCIFI_LAMP_VIRTUAL_POWER_OUTPUT_RID        41
#define UCIFI_LAMP_VOLTAGE_MAX_DIM_RID             42
#define UCIFI_LAMP_VOLTAGE_MIN_DIM_RID             43
#define UCIFI_LAMP_SOURCE_VOLTAGE_RID              44
#define UCIFI_LAMP_SOURCE_CURRENT_RID              45
#define UCIFI_LAMP_SOURCE_POWER_RID                46
#define UCIFI_LAMP_SOURCE_ENERGY_RID               47
/* 48 per spec: Maximum light source current */
#define UCIFI_LAMP_MAX_LIGHT_SOURCE_CURRENT_RID    48
#define UCIFI_LAMP_FADE_TIME_DEFAULT_RID           49
#define UCIFI_LAMP_MANUAL_OVERRIDE_START_TIME_RID  50
#define UCIFI_LAMP_MANUAL_OVERRIDE_END_TIME_RID    51
#define UCIFI_LAMP_FADE_TIME_OVERRIDE_RID          52
#define UCIFI_LAMP_DEFAULT_OVERRIDE_DURATION_RID   53
/* 54 per spec: Manual override active (Boolean, R) */
#define UCIFI_LAMP_MANUAL_OVERRIDE_ACTIVE_RID      54
/* 55 per spec: Default Light color temperature (Integer, RW) */
#define UCIFI_LAMP_DEFAULT_LIGHT_COLOR_TEMPERATURE_RID 55
#define UCIFI_LAMP_DRIVER_OPERATING_HOURS_RID      56
#define UCIFI_LAMP_DRIVER_OPERATING_HOURS_RESET_RID 57
#define UCIFI_LAMP_MANUFACTURER_GTIN_RID           58
#define UCIFI_LAMP_MANUFACTURER_SERIAL_NUMBER_RID  59
#define UCIFI_LAMP_FIRMWARE_VERSION_RID            60
#define UCIFI_LAMP_DALI_VERSION_RID                61
#define UCIFI_LAMP_CAPABILITIES_BITMASK_RID        63
#define UCIFI_LAMP_LAMP_MAX_OPERATING_HOURS_THRESHOLD_RID 64
#define UCIFI_LAMP_LAMP_MAX_OPERATING_HOURS_EXCEEDED_RID  65
#define UCIFI_LAMP_TIMESTAMP_RID                  5518
#define UCIFI_LAMP_FRACTIONAL_TIMESTAMP_RID       6050
#define UCIFI_LAMP_MEASUREMENT_QUALITY_INDICATOR_RID 6042
#define UCIFI_LAMP_MEASUREMENT_QUALITY_LEVEL_RID  6049

#endif /* __LWM2M_UCIFI_LAMP__ */
